using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using AutomatedTrainer.Models;

namespace AutomatedTrainer.WindowsFormsUI
{
    using AutomatedTrainer.Store;

    public partial class CreateExaminationForm : Form
    {
        private Patient WhosExamination { get; set; }

        public CreateExaminationForm(Patient patient)
        {
            InitializeComponent();
            CustomInitialize();

            WhosExamination = patient;
            WhosExaminationLabel.Text = patient.FullName;
        }

        /// <summary>
        /// Because InitializeComponent is generated by the construcor
        /// you can change it but after any change made in the constructor
        /// your code will be lost.
        /// </summary>
        public void CustomInitialize()
        {
            //PhysicalIndicators
            PhysicalIndicatorsPicker.Items.AddRange(Store.Instance.GetPhysicalIndicators());
            //
        }

        private void Submit_Click(object sender, EventArgs e)
        {
            Examination examination = new Examination(Date.Value, Type.Text,
                                        PhysicalIndicatorsPicker.CheckedItems.OfType<PhysicalIndicator>());

            WhosExamination.Examinations.Add(examination);

            this.Close();
        }

    }
}
